<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
   <title>Zend Framework - View e Controller</title>
</head>
<body>
   <h2>Home</h2>
   <?php if($this->username): ?>
       <p>Olá <?php echo $this->username; ?>.</p>
   <?php endif; ?>
</body>
</html>